In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('resultados_recomendaciones.csv')

In [3]:
print(df.info())
df.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6134 entries, 0 to 6133
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     6134 non-null   object
 1   Article_title            6134 non-null   object
 2   Stock_symbol             6134 non-null   object
 3   Url                      6134 non-null   object
 4   Article                  6134 non-null   object
 5   Lsa_summary              6134 non-null   object
 6   Luhn_summary             6134 non-null   object
 7   Textrank_summary         6134 non-null   object
 8   Lexrank_summary          6134 non-null   object
 9   texto_full               6134 non-null   object
 10  tickers_encontrados      6134 non-null   object
 11  n_tokens_con_especiales  6134 non-null   int64
 12  n_chunks                 6134 non-null   int64
 13  n_cortes                 6134 non-null   int64
 14  pos_chunk_1              6134 non-null   float64
 15  neu_chunk_1              6134 non-null   float64
 16  neg_chunk_1              6134 non-null   float64
 17  pos_total                6134 non-null   float64
 18  neu_total                6134 non-null   float64
 19  neg_total                6134 non-null   float64
 20  sentiment_label          6134 non-null   object
 21  n_actual_chunks          6134 non-null   int64
 22  row_idx                  6134 non-null   int64
 23  len_tickers              6134 non-null   int64
 24  ticker_individual        6134 non-null   object
 25  recomendacion_inversion  6134 non-null   int64
dtypes: float64(6), int64(7), object(13)
memory usage: 1.2+ MB
None

,Date,Article_title,Stock_symbol,Url,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary,texto_full,...,neg_chunk_1,pos_total,neu_total,neg_total,sentiment_label,n_actual_chunks,row_idx,len_tickers,ticker_individual,recomendacion_inversion
0,2023-08-01,"Technology Sector Update for 08/01/2023: ZBRA,...",PMAY,https://www.nasdaq.com/articles/technology-sec...,Technology stocks were slipping premarket Tues...,Technology stocks were slipping premarket Tues...,Analysts polled by Capital IQ expected $3.28. ...,Zebra Technologies (ZBRA) was shedding over 18...,Technology stocks were slipping premarket Tues...,"Technology Sector Update for 08/01/2023: ZBRA,...",...,0.969929,0.013106,0.016965,0.969929,negative,1,5,8,UBER,4
1,2023-08-01,Transportation ETFs Rally on Soft Landing Opti...,FDEV,https://www.nasdaq.com/articles/transportation...,Stocks continue to power ahead on rising hopes...,Stocks continue to power ahead on rising hopes...,The iShares U.S. Transportation ETF IYT tracks...,It is the cheapest product in the space. To le...,The iShares U.S. Transportation ETF IYT tracks...,Transportation ETFs Rally on Soft Landing Opti...,...,0.046845,0.042563,0.910592,0.046845,neutral,1,104,16,TSLA,1

In [4]:
df.columns

Index(['Date', 'Article_title', 'Stock_symbol', 'Url', 'Article',
       'Lsa_summary', 'Luhn_summary', 'Textrank_summary', 'Lexrank_summary',
       'texto_full', 'tickers_encontrados', 'n_tokens_con_especiales',
       'n_chunks', 'n_cortes', 'pos_chunk_1', 'neu_chunk_1', 'neg_chunk_1',
       'pos_total', 'neu_total', 'neg_total', 'sentiment_label',
       'n_actual_chunks', 'row_idx', 'len_tickers', 'ticker_individual',
       'recomendacion_inversion'],
      dtype='object')

In [5]:
df.drop(columns=['Lsa_summary', 'Luhn_summary', 'Textrank_summary', 'Lexrank_summary',
                 'n_chunks', 'n_cortes', 'pos_chunk_1', 'neu_chunk_1', 'neg_chunk_1',
                 'sentiment_label','n_actual_chunks', 'row_idx', 'len_tickers', 'Stock_symbol' 
                 ], inplace=True)

In [6]:
df.head(2)

,Date,Article_title,Url,Article,texto_full,tickers_encontrados,n_tokens_con_especiales,pos_total,neu_total,neg_total,ticker_individual,recomendacion_inversion
0,2023-08-01,"Technology Sector Update for 08/01/2023: ZBRA,...",https://www.nasdaq.com/articles/technology-sec...,Technology stocks were slipping premarket Tues...,"Technology Sector Update for 08/01/2023: ZBRA,...",['UBER'],246,0.013106,0.016965,0.969929,UBER,4
1,2023-08-01,Transportation ETFs Rally on Soft Landing Opti...,https://www.nasdaq.com/articles/transportation...,Stocks continue to power ahead on rising hopes...,Transportation ETFs Rally on Soft Landing Opti...,"['TSLA', 'UBER']",502,0.042563,0.910592,0.046845,TSLA,1

In [7]:
df.columns

Index(['Date', 'Article_title', 'Url', 'Article', 'texto_full',
       'tickers_encontrados', 'n_tokens_con_especiales', 'pos_total',
       'neu_total', 'neg_total', 'ticker_individual',
       'recomendacion_inversion'],
      dtype='object')

In [8]:
df.rename(columns={'tickers_encontrados': 'tickers_noticia',
                   'n_tokens_con_especiales': 'n_tokens_articulo',
                   'pos_total': 'puntaje_sent_fin_pos',
                   'neg_total': 'puntaje_sent_fin_neg',
                   'neu_total': 'puntaje_sent_fin_neu',
                   'recomendacion_inversion': 'recom_inv_llm'
                   }, inplace=True)

In [9]:
df["idx"] = range(len(df))

In [10]:
df_full_pre_lstm = df.copy()

In [11]:
df_full_pre_lstm.to_csv('dataset_full_pre_lstm.csv', index=False)

In [12]:
df_full_pre_lstm.columns

Index(['Date', 'Article_title', 'Url', 'Article', 'texto_full',
       'tickers_noticia', 'n_tokens_articulo', 'puntaje_sent_fin_pos',
       'puntaje_sent_fin_neu', 'puntaje_sent_fin_neg', 'ticker_individual',
       'recom_inv_llm', 'idx'],
      dtype='object')

In [13]:
df_lstm = df[['Date','puntaje_sent_fin_pos',
              'puntaje_sent_fin_neu', 'puntaje_sent_fin_neg',
               'ticker_individual','recom_inv_llm', 'idx'
                ]].copy()

In [15]:
df_lstm.to_csv('dataset_para_lstm.csv', index=False)