In [29]:
import pandas as pd
import polars as pl
import fsspec
import plotly.express as px
import ast
import json
import numpy as np

In [30]:
#import polars as pl

#df = pl.read_parquet('hf://datasets/fddemarco/pushshift-reddit/**/*.parquet')

[Link al dataset](https://huggingface.co/datasets/finiteautomata/news-argentina)

In [31]:


fs, _, paths = fsspec.get_fs_token_paths("hf://datasets/fddemarco/pushshift-reddit/**/*.parquet")
files = fs.ls(paths[0])

print(files)

[{'name': 'datasets/fddemarco/pushshift-reddit/data/RS_2012-01_00.parquet', 'size': 112243140, 'type': 'file', 'blob_id': 'ab40a869c7772c2e0dafdba11c3b4fba59739fc0', 'lfs': BlobLfsInfo(size=112243140, sha256='e88737be217579ae52349073d5166dc601a1e882e012078fcfd6b2a25625487c', pointer_size=134), 'last_commit': None, 'security': None}]

In [32]:

fs, _, paths = fsspec.get_fs_token_paths("hf://datasets/fddemarco/pushshift-reddit/**/*.parquet")
files_info = fs.ls(paths[0])

# me quedo solo con los nombres (paths completos dentro de hf://)
files = [f"hf://{f['name']}" for f in files_info]

print(files)

['hf://datasets/fddemarco/pushshift-reddit/data/RS_2012-01_00.parquet']

In [33]:
fs, _, paths = fsspec.get_fs_token_paths("hf://datasets/fddemarco/pushshift-reddit/**/*.parquet")
files_info = fs.ls(paths[0])

# Extraigo solo los nombres en formato completo hf://...
files = [f"hf://{f['name']}" for f in files_info if f['name'].endswith(".parquet")]

# Ordeno por nombre (para que respete el orden 00000, 00001, 00002...)
files = sorted(files)

print("Archivos encontrados:")
for f in files:
    print(f)

Archivos encontrados:
hf://datasets/fddemarco/pushshift-reddit/data/RS_2012-01_00.parquet

In [34]:
lf = pl.scan_parquet(
    files,
    cast_options=pl.ScanCastOptions(extra_struct_fields="ignore")
)

pdf = lf.collect()

In [35]:
df = pdf.to_pandas()

print(df.info())

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   author        800000 non-null  object
 1   created_utc   800000 non-null  int64
 2   id            800000 non-null  object
 3   num_comments  800000 non-null  int64
 4   score         800000 non-null  int64
 5   selftext      800000 non-null  object
 6   subreddit     800000 non-null  object
 7   subreddit_id  800000 non-null  object
 8   title         800000 non-null  object
dtypes: int64(3), object(6)
memory usage: 54.9+ MB
None

,author,created_utc,id,num_comments,score,selftext,subreddit,subreddit_id,title
0,doopercooper,1325462399,nz3g9,24,82,,videos,t5_2qh1e,guy chases after runaway car and barely saves ...
1,,1325462398,nz3g8,0,0,,gaming,t5_2qh03,the legend of zelda rap by smosh
2,thiswebpage,1325462398,nz3g7,16,77,,hiphopheads,t5_2rh4c,how i feel about most rap battles
3,belifted,1325462395,nz3g6,0,4,,funny,t5_2qh33,eliot chang spread the word
4,,1325462392,nz3g5,0,1,,leagueoflegends,t5_2rfxx,mordekaiser bored screwin around on ps

In [36]:
df.author.value_counts()

author
                      225442
bonafera                2065
davidreiss666           1943
redditteam              1562
iamtotalcrap            1516
                       ...
pprt5                      1
yunus89115                 1
insuranceclaiminsp         1
raslavernon                1
rbcp                       1
Name: count, Length: 244990, dtype: int64

In [37]:
print(df.subreddit.value_counts().to_string())

subreddit
funny                    51971
pics                     34552
AdviceAnimals            31861
AskReddit                30360
fffffffuuuuuuuuuuuu      26913
trees                    20159
politics                 18334
videos                   17826
gaming                   17821
WTF                      15871
atheism                  12318
Music                    11509
technology               10275
aww                       9911
worldnews                 9753
circlejerk                8453
todayilearned             8235
reportthespammers         5802
skyrim                    5524
leagueoflegends           5448
SteamGameSwap             5407
tf2trade                  5157
firstworldproblems        5144
starcraft                 4731
general                   4596
movies                    4542
Minecraft                 4349
askscience                4237
mylittlepony              4135
bestof                    4125
gonewild                  3701
science                   3611
news                      3440
swtor                     3427
business                  3416
SteamTrade                3370
ronpaul                   3120
buildapc                  3015
IAmA                      2796
nsfw                      2787
offbeat                   2523
battlefield3              2517
nfl                       2470
Health                    2215
Android                   2143
nsfw_videos               2126
Libertarian               2114
TwoXChromosomes           2111
sports                    1896
travel                    1892
Fitness                   1888
SOPA                      1884
soccer                    1777
itookapicture             1773
listentothis              1756
guns                      1714
food                      1636
techsupport               1590
gifs                      1575
mazaodds                  1562
atheismbot                1517
tf2                       1513
AnythingGoesNews          1497
malefashionadvice         1492
LadyBoners                1471
Games                     1456
comics                    1422
occupywallstreet          1421
conspiracy                1419
Christianity              1363
Art                       1346
sex                       1334
cats                      1323
tipofmytongue             1272
photography               1245
explainlikeimfive         1233
keto                      1215
pokemon                   1195
dubstep                   1192
hockey                    1176
entertainment             1168
loseit                    1163
nba                       1157
Metal                     1137
doctorwho                 1134
mw3                       1129
gameswap                  1127
hiphopheads               1116
relationships             1112
CFB                       1111
gentlemanboners           1071
books                     1054
ragecomics                1054
lgbt                      1041
anime                     1021
r4r                       1002
electronicmusic            995
WeAreTheMusicMakers        979
worldpolitics              974
wow                        965
magicTCG                   961
DoesAnybodyElse            932
canada                     921
cars                       898
Guitar                     885
programming                870
DotA2                      849
mcservers                  840
gossip                     830
apple                      804
Drugs                      797
NoFap                      792
zelda                      792
webcomics                  789
secretsanta                785
Economics                  765
RedditLaqueristas          764
motorcycles                750
environment                746
EarthPorn                  742
writing                    733
shittyaskscience           729
TechNewsToday              721
SquaredCircle              712
india                      712
OkCupid                    707
iphone                     697
self                       691
unitedkingdom              677
stopsmoking                668
comicbooks                 666
education                  664
Cooking                    657
MMA                        656
darksouls                  654
fashion                    645
gaymers                    644
ForeverAlone               642
bicycling                  642
fitnesscirclejerk          641
amiugly                    639
Random_Acts_Of_Pizza       633
cigars                     628
teenagers                  621
GetMotivated               617
seduction                  614
4chan                      600
StarWars                   592
Parenting                  577
harrypotter                576
BTFC                       575
tattoos                    573
TrueReddit                 571
runescape                  571
humor                      571
Homebrewing                568
casualiama                 567
MLPLounge                  566
snowboarding               563
Conservative               562
Autos                      561
space                      560
MensRights                 553
Design                     552
Poetry                     549
relationship_advice        547
community                  540
learnprogramming           538
nyc                        527
running                    520
gadgets                    518
ShitRedditSays             514
LifeProTips                514
none                       511
depression                 510
WorkoutSex                 509
photocritique              505
promos                     503
nosleep                    500
television                 499
wallpapers                 487
progressive                486
GoneWildPlus               484
Boobies                    482
australia                  477
ass                        476
sysadmin                   474
web_design                 474
Frugal                     471
beer                       471
FoodPorn                   471
chicago                    469
DIY                        469
CityPorn                   465
hardware                   463
treemusic                  461
rpg                        458
applehelp                  454
fifthworldproblems         454
dogs                       450
AnarchistNews              449
AnythingGoesPics           448
shutupandtakemymoney       448
linux                      447
geek                       444
AmISexy                    436
NSFW_GIF                   435
randomsexiness             435
Celebs                     433
jobs                       427
woahdude                   421
dating_advice              421
Seattle                    421
Military                   420
ladybonersgw               418
ragenovels                 413
startrek                   410
toronto                    409
Terraria                   408
creepy                     408
dungeondefenders           399
history                    399
Jokes                      392
investing                  391
Images                     391
SEO                        389
meme                       387
personalfinance            385
vinyl                      384
Paleo                      384
Frisson                    380
breakingbad                376
finance                    376
Anarchism                  374
law                        371
Israel                     370
drunk                      369
skateboarding              368
Austin                     367
treecomics                 366
wicked_edge                362
gameofthrones              361
electrohouse               361
picrequests                360
new_right                  359
gamedev                    359
DnB                        356
MakeupAddiction            355
EndlessWar                 353
math                       352
Pets                       351
Photobucketplunder         351
trance                     350
LosAngeles                 350
economy                    350
islam                      347
recipes                    346
Hardwarenews               346
video                      346
AndroidQuestions           345
SuicideWatch               344
scifi                      341
wallpaper                  340
Bondage                    339
answers                    333
RandomKindness             333
facebook                   331
Documentaries              324
zombies                    321
software                   318
catpictures                317
EnoughPaulSpam             316
Animals                    316
religion                   316
Portland                   315
marketing                  313
mexico                     313
nostalgia                  312
HeroesofNewerth            309
RealEstate                 308
IDAP                       308
pornvids                   306
Favors                     304
Aquariums                  304
Steam                      304
gamernews                  300
futurebeats                300
TheSimpsons                299
fantasybball               298
socialmedia                295
Eve                        287
porn                       286
C25K                       285
psychology                 284
PS3                        283
Watches                    281
freebies                   281
gamemusic                  280
playitforward              279
Coffee                     279
Assistance                 278
LegalTeens                 276
PoliticalHumor             275
skeptic                    275
baseball                   273
punk                       271
webdev                     271
philosophy                 271
Bad_Cop_No_Donut           270
forhire                    270
AsianHotties               270
Astronomy                  269
longboarding               268
Amateur                    268
cripplingalcoholism        267
52weeksofcooking           267
skiing                     266
Denver                     265
HardcoreSMP                265
DAE                        264
spacedicks                 262
Marijuana                  262
RealGirls                  262
japan                      261
SRSBusiness                259
adventuretime              258
misc                       254
jailbreak                  254
katawashoujo               252
Internet                   252
newreddits                 250
ireland                    248
Jazz                       248
kpop                       247
Shopping                   246
stopdrinking               244
facepalm                   243
Warhammer                  242
doodleordie                242
gamecollecting             242
dvdcollection              241
49ers                      241
exmormon                   240
BreakUps                   238
realdubstep                238
drums                      238
google                     237
boardgames                 236
dogpictures                235
DJs                        234
energy                     234
cosplay                    233
Psychonaut                 232
IWantToLearn               231
offmychest                 231
ipad                       231
architecture               229
engineering                229
Diablo                     228
stocks                     228
Atlanta                    227
biology                    225
classicalmusic             225
philadelphia               224
beerporn                   223
ggggg                      223
Judaism                    222
penis                      222
sweden                     221
3DS                        221
aviation                   220
actuallesbians             220
halo                       220
formula1                   220
battlestations             219
computers                  219
Tgirls                     219
netsec                     217
electronics                217
ps3bf3                     216
2012Elections              216
help                       216
BabyBumps                  216
HumanPorn                  214
gamingpc                   213
wikipedia                  212
Bass                       210
climbing                   210
shittyadvice               209
memes                      209
batman                     208
boston                     207
LinuxActionShow            206
masseffect                 206
ukpolitics                 206
audiophile                 206
Glitch_in_the_Matrix       204
AlbumArtPorn               204
Gunners                    203
GalaxyNexus                203
horror                     202
FIFA12                     202
SpideyMeme                 202
hardbodies                 201
mashups                    200
london                     199
lego                       199
vancouver                  198
hotties                    198
steamtrades                198
gardening                  198
Buddhism                   197
asoiaf                     197
Scotch                     197
LiverpoolFC                197
PhxClassWarCouncil         197
GirlsWithHeadphones        196
ClopClop                   196
Blogging                   195
AbandonedPorn              195
MTB                        194
Enhancement                194
steamswap                  194
Foodforthought             193
HistoryPorn                193
asmr                       191
HIMYM                      190
Ubuntu                     190
GreenBayPackers            189
ThisIsOurMusic             189
Anarcho_Capitalism         189
asktransgender             187
redditrequest              187
europe                     187
coversongs                 186
Sherlock                   186
Rateme                     186
malehairadvice             185
screenshots                185
IndieGaming                185
de                         184
webdesign                  184
fantasyfootball            184
beatles                    183
sanfrancisco               183
Bitcoin                    183
youtube                    183
washingtondc               183
reactiongifs               182
MLPdrawingschool           182
homestuck                  182
socialism                  181
houston                    181
wp7dev                     181
truegaming                 181
carporn                    181
tipofmypenis               181
startups                   179
Maplestory                 179
firstimpression            179
newzealand                 179
vegan                      178
SuggestALaptop             178
steamcoupons               178
transgender                178
montreal                   177
OperationPullRyan          177
thick                      176
Adgeek                     176
dwarffortress              176
YouShouldKnow              176
windows                    176
yugioh                     175
xbox360                    174
CIRCLEJERKMILITIA          174
Awww                       174
dirtypenpals               174
weightroom                 174
coupons                    174
AnimalPorn                 173
DebateReligion             173
obama                      172
Entrepreneur               172
PrettyGirls                171
PoliticalDiscussion        171
WorldofTanks               170
waterporn                  170
Filmmakers                 170
VillagePorn                168
Coachella                  168
SkyPorn                    168
edmproduction              167
knitting                   167
mflb                       166
letsplay                   164
NetflixBestOf              164
MLS                        164
forza                      164
minerapocalypse            164
Graffiti                   163
knives                     163
Scotland                   163
Physics                    162
ottawa                     162
MMFB                       162
Cartalk                    161
DesktopDetective           161
askseddit                  161
manga                      161
TrollXChromosomes          161
football                   160
CollegeBasketball          160
headphones                 160
networking                 160
beards                     159
MvC3                       159
ifyoulikeblank             158
asustransformer            158
kindle                     158
feet                       157
women                      157
Baking                     157
ents                       156
quotes                     156
House                      156
China                      155
arresteddevelopment        155
Home                       155
france                     155
Cuckold                    154
gamesell                   151
Punny                      150
daddit                     150
arduino                    148
Republican                 148
crafts                     148
Fallout                    147
nsfw_gifs                  147
AskWomen                   147
cordcutters                147
nature                     147
texas                      146
Wordpress                  146
poker                      145
somethingimade             145
bjj                        144
dating                     144
airsoft                    144
ravens                     143
GoogleYourUsername         143
pittsburgh                 143
Feminism                   142
realasians                 142
polyamory                  142
Piracy                     141
shamelessplug              141
mac                        140
chrome                     140
Catholicism                140
GaymersGoneMild            139
microgrowery               138
wedding                    138
QuotesPorn                 137
javascript                 137
Dexter                     137
brisbane                   137
Dallas                     137
futuregarage               137
MilitaryPorn               137
SRSDiscussion              136
Demotivational             136
androiddev                 136
gaymersgonewild            136
Cricket                    136
rit                        136
InteriorDesign             135
radiohead                  135
CHIBears                   135
beermoney                  134
pornaddicts                134
mylittleandysonic1         134
strictlyworldpolitics      134
beauty                     133
chess                      132
howto                      131
pokemontrades              131
sandiego                   131
Romania                    131
NYGiants                   131
tall                       131
selfhelp                   131
disney                     130
Python                     130
hardwareswap               130
piano                      130
furry                      130
HomeworkHelp               130
RumourMill                 129
BostonBruins               129
happy                      129
talesfromtechsupport       129
wp7                        129
entwives                   129
milf                       128
discgolf                   128
Naruto                     128
racism                     127
advertising                127
LongDistance               127
feminisms                  127
treesgonewild              126
FinancialPlanning          126
Fishing                    125
Metalcore                  125
GearsOfWar                 125
LawSchool                  125
animation                  124
futurama                   124
photoshop                  124
AMA                        124
coys                       124
medicine                   123
steelers                   123
Hardcore                   123
Great_Cumshot_Pics         122
RedditThroughHistory       122
literature                 122
WeAreTheFilmMakers         122
TheoryOfReddit             122
eagles                     122
CampingandHiking           121
nintendo                   121
yoga                       121
crochet                    120
SexyButNotPorn             120
androidapps                119
FreeKarma                  119
Hotwife                    118
Tribes                     118
surfing                    118
bindingofisaac             118
omegle                     118
Insurance                  118
pakistan                   118

In [38]:
## Transformar Data y crear columnas complementarias
# transformar created_at a yyyy-mm-dd
df["Fecha"] = pd.to_datetime(df["created_utc"], unit="s").dt.date

In [39]:
df.head()

,author,created_utc,id,num_comments,score,selftext,subreddit,subreddit_id,title,Fecha
0,doopercooper,1325462399,nz3g9,24,82,,videos,t5_2qh1e,guy chases after runaway car and barely saves ...,2012-01-01
1,,1325462398,nz3g8,0,0,,gaming,t5_2qh03,the legend of zelda rap by smosh,2012-01-01
2,thiswebpage,1325462398,nz3g7,16,77,,hiphopheads,t5_2rh4c,how i feel about most rap battles,2012-01-01
3,belifted,1325462395,nz3g6,0,4,,funny,t5_2qh33,eliot chang spread the word,2012-01-01
4,,1325462392,nz3g5,0,1,,leagueoflegends,t5_2rfxx,mordekaiser bored screwin around on ps,2012-01-01

In [40]:
print(df.Fecha.min(), 
df.Fecha.max())

2012-01-01 2012-01-13